[project]
name = "lyrics"
version = "0.2.0"
requires-python = ">=3.11"
dependencies = [
    "syncedlyrics",
    "pympris>=1.4",
    "dbus-python>=1.3.0",
    "PyGObject>=3.42.0",
]

[project.scripts]
lyrics = "universal_lyrics:main"
